version: "3.0"
services:
  server:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "5000:5200"
  web:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.web
    ports:
      - "80:80"