version: "3.0"

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "4200:80"
    volumes:
      - ./:/usr/share/easybsb
