name: CompileAndTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CompileAndTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npx nx run-many --target=lint --all
      - run: npm run build:all
      - run: npm run e2e
