name: CompileAndTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CompileAndTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - run: npm version
      - run: npm ci
      - run: npm run build:all
      - run: npm run e2e
